#define  cdtt   0
#define  cEPSMIN   1
#define  cZLIGHT   2
#define  cCHLC   3
#define  cZres   4
#define  cSF   5
#define  csimyear   6
#define  cANSFMIN   7
#define  cAPSFMAX   8
#define  cAPSFMIN   9
#define  cAPSFT   10
#define  cAZMAX   11
#define  cAZMIN   12
#define  cDTA   13
#define  cDTB   14
#define  cDTC   15
#define  cDTMIN   16
#define  cEPSD   17
#define  cGI   18
#define  cGMAX   19
#define  cGMIN   20
#define  cKANSF   21
#define  cKAPSF   22
#define  cKDEN   23
#define  cKNDST   24
#define  cKMINER   25
#define  cKMO   26
#define  cKPSED   27
#define  cKSEZA   28
#define  cKSRFMAX   29
#define  cKXG   30
#define  cKXMIN   31
#define  cKZMIN   32
#define  cLGH   33
#define  cLGL   34
#define  cLINDEN   35
#define  cLTMAX   36
#define  cLXH   37
#define  cLXHN   38
#define  cLXL   39
#define  cLXLN   40
#define  cMGH   41
#define  cMGL   42
#define  cMOMIN   43
#define  cMOT   44
#define  cMXH   45
#define  cMXL   46
#define  cNDSSTART   47
#define  cNDSEND   48
#define  cNDSMAX   49
#define  cKNDS   50
#define  cOPTNP   51
#define  cPF   52
#define  cR   53
#define  cRAT   54
#define  cRATF   55
#define  cRATN   56
#define  cRATNF   57
#define  cRL   58
#define  cRLW   59
#define  cRXMF   60
#define  cRZMIN   61
#define  cRZOPT   62
#define  cRZTMIN   63
#define  cEPSR   64
#define  cTOPTZ   65
#define  cUXZD   66
#define  cVD   67
#define  cVMIG   68
#define  cWPKX   69
#define  cWPKZ   70
#define  cYD   71
#define  cYND   72
#define  cYNX   73
#define  cYOX   74
#define  cYZN   75
#define  cYZP   76
#define  cSEZMAX   77
#define  cKO   78
#define  cVO2ATM 79
#define  cNpsfmode 80
#define  cSrfmode  81
#define  cXminermode 82

#define  pphyton   0
#define  pEPSX   1
#define  pBETA   2
#define  pGAMMAX   3
#define  pGAMMIN   4
#define  pKI   5
#define  pKN   6
#define  pKP   7
#define  pKPF   8
#define  pNFIX   9
#define  pPFC   10
#define  pPFX   11
#define  pPHOTXMAX   12
#define  pPHOTXMIN   13
#define  pRXTMIN   14
#define  pRXTOPT   15
#define  pRXTSLOPE   16
#define  pTOPTX   17
#define  pUXZ   18
#define  pVS   19
#define  pYX   20
#define  pZETA   21
#define  undt   0
#define  uvol   1
#define  udepth   2
#define  uzmix   3
#define  uqin   4
#define  uased   5
#define  usrf   6
#define  uiin   7
#define  utemp   8
#define  unin   9
#define  upin   10
#define  upomin   11
#define  uzin   12
#define  uoin   13
#define  uaver   14
#define  uad   15
#define  uau   16
#define  uDi   17
#define  ux1in   18
#define  ux2in   19
#define  ux3in   20
#define  usf   21
